const express=require('express');const cors=require('cors');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const app=express(),PORT=3001,DB=path.join(__dirname,'data','db.json'),SECRET='mock-hmac-secret';app.use(cors());app.use(express.json());
const users=[{username:'admin',password:'Admin@123456',role:'admin',name:'管理员'},{username:'operator',password:'Operator@123456',role:'operator',name:'操作员'},{username:'auditor',password:'Auditor@123456',role:'auditor',name:'审计员'}];
function seed(){return{device:{name:'IDN-Policy-VM',vendor:'模拟安全科技',version:'V1.0.0-demo',model:'IDN-PM-1000',serial:'SN-20260619-0001'},regions:[{id:crypto.randomUUID(),name:'总部园区',code:'HQ',desc:'核心办公区域'},{id:crypto.randomUUID(),name:'数据中心',code:'DC',desc:'业务承载区域'}],orgs:[],apps:[],intents:[],policies:[],logs:[],alerts:[{id:crypto.randomUUID(),level:'高',msg:'授时状态短暂异常',time:new Date().toISOString()}]}}
function read(){if(!fs.existsSync(DB)){const d=seed();d.orgs=[{id:crypto.randomUUID(),name:'研发部',regionId:d.regions[0].id,desc:'研发组织'},{id:crypto.randomUUID(),name:'运维部',regionId:d.regions[1].id,desc:'运维组织'}];d.apps=[{id:crypto.randomUUID(),name:'OA门户',regionId:d.regions[0].id,orgId:d.orgs[0].id,permission:'内网访问',ip:'10.10.1.20',status:'运行中',createdAt:new Date().toISOString()},{id:crypto.randomUUID(),name:'工单系统',regionId:d.regions[1].id,orgId:d.orgs[1].id,permission:'授权访问',ip:'10.20.1.30',status:'运行中',createdAt:new Date().toISOString()}];write(d);return d}return JSON.parse(fs.readFileSync(DB,'utf8'))}function write(d){fs.writeFileSync(DB,JSON.stringify(d,null,2))}
function sign(l){return crypto.createHmac('sha256',SECRET).update(`${l.username}|${l.action}|${l.time}`).digest('hex')}function log(db,username,action){const l={id:crypto.randomUUID(),username:username||'system',action,time:new Date().toISOString(),audited:false,status:'未审计'};l.hmac=sign(l);db.logs.unshift(l)}function ok(res,data){res.json({success:true,data})}
function names(db,x){return{...x,regionName:db.regions.find(r=>r.id===x.regionId)?.name||'',orgName:db.orgs.find(o=>o.id===x.orgId)?.name||''}}
app.post('/api/login',(req,res)=>{const u=users.find(x=>x.username===req.body.username&&x.password===req.body.password);const db=read();log(db,req.body.username,u?'登录成功':'登录失败');write(db);if(!u)return res.status(401).json({success:false,message:'账号或密码错误'});ok(res,{username:u.username,role:u.role,name:u.name})});
app.get('/api/dashboard',(req,res)=>{const db=read();ok(res,{device:db.device,counts:{regions:db.regions.length,orgs:db.orgs.length,apps:db.apps.length,policies:db.policies.length,logs:db.logs.length,alerts:db.alerts.length}})});
app.get('/api/situation',(req,res)=>ok(res,{deviceStatus:[92,96,88,99],dr:{主中心:8,备中心:6,同步中:2},apps:{运行中:12,维护中:2,停用:1},interfaces:[120,180,150,260,210,300,280],platform:{cpu:36,mem:58,disk:42},timeAlerts:['NTP 服务正常','最近一次校时：2026-06-19 08:00:00']}));
function crud(name){app.get(`/api/${name}`,(req,res)=>{const db=read();let arr=db[name];if(name==='apps')arr=arr.map(a=>names(db,a));if(name==='orgs')arr=arr.map(o=>({...o,regionName:db.regions.find(r=>r.id===o.regionId)?.name||''}));if(req.query.q)arr=arr.filter(x=>JSON.stringify(x).includes(req.query.q));ok(res,arr)});app.post(`/api/${name}`,(req,res)=>{const db=read();const item={id:crypto.randomUUID(),...req.body};if(name==='apps')item.createdAt=new Date().toISOString();db[name].unshift(item);log(db,req.body.username,`新增${name}:${item.name||item.intentName}`);write(db);ok(res,item)});app.put(`/api/${name}/:id`,(req,res)=>{const db=read();const i=db[name].findIndex(x=>x.id===req.params.id);db[name][i]={...db[name][i],...req.body};log(db,req.body.username,`修改${name}:${db[name][i].name||db[name][i].intentName}`);write(db);ok(res,db[name][i])});app.delete(`/api/${name}/:id`,(req,res)=>{const db=read();const old=db[name].find(x=>x.id===req.params.id);db[name]=db[name].filter(x=>x.id!==req.params.id);log(db,req.query.username,`删除${name}:${old?.name||old?.intentName||req.params.id}`);write(db);ok(res,true)})}['regions','orgs','apps','intents'].forEach(crud);
app.post('/api/intents/:id/generate',(req,res)=>{const db=read();const it=db.intents.find(x=>x.id===req.params.id);if(!it)return res.status(404).json({success:false});const conflict=db.policies.some(p=>p.sourceRegionId===it.sourceRegionId&&p.sourceOrgId===it.sourceOrgId&&p.targetAppId===it.targetAppId&&p.protocol===it.protocol&&String(p.port)===String(it.port)&&['允许','拒绝'].includes(p.action)&&['允许','拒绝'].includes(it.action)&&p.action!==it.action);const policy={id:crypto.randomUUID(),intentId:it.id,name:`策略-${it.intentName}`,sourceRegionId:it.sourceRegionId,sourceOrgId:it.sourceOrgId,targetAppId:it.targetAppId,action:it.action,protocol:it.protocol,port:it.port,effectiveTime:it.effectiveTime,priority:it.priority,status:conflict?'冲突':'停用',rule:`FROM ${it.sourceOrgName||it.sourceOrgId} TO APP ${it.targetAppName||it.targetAppId} ${it.action} ${it.protocol}/${it.port}`,conflict,createdAt:new Date().toISOString()};db.policies.unshift(policy);log(db,req.body.username,`生成策略:${policy.name}${conflict?'（发现冲突）':''}`);write(db);ok(res,policy)});
app.get('/api/policies',(req,res)=>{const db=read();ok(res,db.policies)});app.patch('/api/policies/:id/status',(req,res)=>{const db=read();const p=db.policies.find(x=>x.id===req.params.id);p.status=req.body.status;log(db,req.body.username,`${req.body.status}策略:${p.name}`);write(db);ok(res,p)});app.delete('/api/policies/:id',(req,res)=>{const db=read();db.policies=db.policies.filter(x=>x.id!==req.params.id);log(db,req.query.username,'删除策略');write(db);ok(res,true)});
app.get('/api/logs',(req,res)=>{const db=read();let arr=db.logs.map(l=>({...l,integrity:sign(l)===l.hmac?'完整':'疑似篡改'}));if(req.query.q)arr=arr.filter(x=>JSON.stringify(x).includes(req.query.q));ok(res,arr)});app.patch('/api/logs/:id/audit',(req,res)=>{const db=read();const l=db.logs.find(x=>x.id===req.params.id);l.audited=true;l.status='已审计';write(db);ok(res,l)});app.delete('/api/logs/:id',(req,res)=>{const db=read();db.logs=db.logs.filter(x=>x.id!==req.params.id);write(db);ok(res,true)});
app.listen(PORT,()=>console.log(`API http://localhost:${PORT}`));
